kind: pipeline
name: default

steps:
  - name: test
    image: maven:3.6.3-jdk-8
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B

  - name: docker
    image: plugins/docker
    settings:
      repo: chrishopkins53/tm470-drone
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master