version: 2.1

orbs:
  maven: circleci/maven@1.0.1
  ruby: circleci/ruby@1.0.5
  node: circleci/node@3.0.1

jobs:

  build-java-docker:
    environment:
      IMAGE_NAME: chrishopkins53/tm470-circleci
    docker:
      - image: circleci/openjdk:latest
    steps:
      - setup_remote_docker
      - run:
          name: Compile Jar
          command: mvn install -DskipTests
      - run:
          name: Build Docker image
          command: |
            cd tm470-java && docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  publish-latest:
    environment:
      IMAGE_NAME: chrishopkins53/tm470-circleci
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$docker_password" | docker login --password-stdin --username "$docker_username"
            docker push $IMAGE_NAME:latest

  run-rails:
    working_directory: ~/tm470-circleci/tm470-rails
    docker:
      - image: circleci/ruby:2.6.4-node
    steps:
      - checkout:
          path: ~/tm470-circleci
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          app-dir: ~/tm470-circleci/tm470-rails
      - run:
          name: Start rails server
          command: bundle exec rails s


  run-java:
    working_directory: ~/tm470-circleci/tm470-java
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - run:
          name: Start java app
          command: mvn spring-boot:run

  run-automation-tests:
    working_directory: ~/tm470-circleci/functional-tests
    docker:
      - image: circleci/ruby:2.6.4-node-browsers
    steps:
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for rails
          command: dockerize -wait http://run-rails:3000 -timeout 5m
      - run:
          name: Wait for java
          command: dockerize -wait http://run-java:8000 -timeout 5m


workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results

  functional-test:
    jobs:
      - run-rails
      - run-java
      - run-automation-tests


  build-master:
    jobs:
      - build-java-docker:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build-java-docker
          filters:
            branches:
              only: master
