version: 2.1

orbs:
  maven: circleci/maven@1.0.1

jobs:
  build:
    environment:
      IMAGE_NAME: chrishopkins53/tm470-circleci
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Compile Jar
          command: mvn install -DskipTests
      - run:
          name: Build Docker image
          command: |
            cd tm470-java && docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    environment:
      IMAGE_NAME: chrishopkins53/tm470-circleci
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$docker_password" | docker login --password-stdin --username "$docker_username"
            docker push $IMAGE_NAME:latest

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results

  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
